name: Neon Database Backup

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  create-neon-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Manage Neon Database Backups
        env:
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}
          MAX_BACKUPS: 5
        run: |
          # Création d'un nom de branche avec la date
          BACKUP_NAME="backup-$(date +%Y-%m-%d)"

          # Créer une nouvelle branche de sauvegarde
          echo "Création de la nouvelle sauvegarde: $BACKUP_NAME"
          RESPONSE=$(curl -s -X POST "https://console.neon.tech/api/v2/projects/$NEON_PROJECT_ID/branches" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $NEON_API_KEY" \
            -H "Accept: application/json" \
            -d "{\"branch\": {\"name\": \"$BACKUP_NAME\"}}")

          # Vérifier si la création a réussi
          if echo "$RESPONSE" | grep -q "id"; then
            echo "✅ Sauvegarde Neon créée avec succès: $BACKUP_NAME"
            
            # Nettoyer les anciennes branches si nécessaire
            echo "Récupération des branches existantes..."
            BRANCHES=$(curl -s -X GET "https://console.neon.tech/api/v2/projects/$NEON_PROJECT_ID/branches" \
              -H "Accept: application/json" \
              -H "Authorization: Bearer $NEON_API_KEY")
            
            # Compter les branches de sauvegarde
            BACKUP_COUNT=$(echo "$BRANCHES" | grep -o "backup-" | wc -l)
            
            if [ $BACKUP_COUNT -gt $MAX_BACKUPS ]; then
              echo "Nettoyage des anciennes sauvegardes nécessaire ($BACKUP_COUNT/$MAX_BACKUPS max)"
              # Liste des branches pour debug
              echo "$BRANCHES" | grep -o '"name":"backup-[^"]*"' | sort
            else
              echo "Nombre de sauvegardes actuel: $BACKUP_COUNT/$MAX_BACKUPS max"
            fi
          else
            echo "❌ Échec de la création de la sauvegarde"
            echo "Réponse: $RESPONSE"
          fi

      - name: Notify backup status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Sauvegarde Neon réussie ✅"
          else
            echo "Échec de la sauvegarde Neon ❌"
          fi
